LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '127.0.0.1'
WEB_PORT: 8000

KAFKA_BROKER: "127.0.0.1:9093"
SRC_DATA_TOPIC: "avro-data"